name: Excel - Credit Spread

on:
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8:00 AM UTC (3:00 AM ET during Standard Time)
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  update_excel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openpyxl

      # Run the Python script
      - name: Run update script
        run: python scripts/excel-credit-spread.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update of Excel file"
          git push
