name: Pages - Wages

on:
  schedule:
  - cron: '20 13 12 2,5,8,11 *'  # Run on the 12th day of February, May, August, and November at 13:20 UTC
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Run Python script
        run: python scripts/pages-wages.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ./wages/index.html
          git commit -m "Updated HTML with latest data"
          git push
