name: Update CNBC News Mobile

on:
  schedule:
    - cron: "*/240 * * * *" # Run every 240 minutes
  workflow_dispatch:        # Allow manual triggering

permissions:
  contents: write

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use the latest Python 3 version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests

      # Step 4: Run the Python script
      - name: Run Python script
        run: python scripts/generate-cnbc-news-mobile.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add news_mobile.html
          git commit -m "Update news_mobile.html with latest CNBC news"
          git push
